
---
## FIFA FNDA-28031 (TQBVT_PROD) - 3rd number block is automatically added
- https://jira.tsl.telus.com/browse/FNDA-28031


//Original Offer
Call Guardian - 3rd Number Billing Block-1
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/7d7ebec3-7bee-c833-e75d-5d31b07b615a/207762ee-dd0a-4386-bdd4-74a967836320


//New Product Offering
3rd Number Block feature offer
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/c0012f52-866f-44e5-9be3-17d1aba7bb29/3818118c-53ab-4acf-9e61-7c0a25418318

DV27
ccbp fqc ii
113805333

unounouno dosdosdos

En ITN04
A A2386
102857449

itn04
tien ofor

ping pong

---
<br/><br/><br/>

---
## FIFA FNDA-27866 (TQBVT_PROD) - Display block feature on Home phone is not working
- https://jira.tsl.telus.com/browse/FNDA-27866

Display Block
9160233552813596001
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/c986ae06-0df8-059c-6dca-3b712ec6b24d/207762ee-dd0a-4386-bdd4-74a967836320


Add Disp Block feature offer
9164912403320407836
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/5a36fddc-dfa5-495c-b442-7ca614470967/3818118c-53ab-4acf-9e61-7c0a25418318

--- 
<br/><br/><br/>



---
## FIFA FNDA-27898 [TnM-API] [ITSS-4936] || Incorrect Tax Calculation for One time TIC promotion "Referral One Time LWC Credit $50" in NC BE
- https://jira.tsl.telus.com/browse/FNDA-27898

- [link](./stuff/CLOSED/FNDA-27898/index.md)

Adiccbpcsr RBdecsevencsrthree
alain dryrunthree
nelsontest RBnovfive

CR Incorrect Tax Calculation for One time TIC 
ITN02

--- 
<br/><br/><br/>




---
## TAFT 2.0 Delivery TAFT2-7753 [PC] Create script for datafix
- https://jira.tsl.telus.com/browse/TAFT2-7753

- [link](./stuff/TAFT2-7753)
- https://docs.google.com/spreadsheets/d/1OPwL9XbnQGKyujvoN-5dd4gU6aR7NVGe/edit##gid=898730481


ITN02 Adiccbpcsr RBnovfourteencsr
ITN03 aagrrhpccbp aagrrhp

--- 
<br/><br/><br/>


---
## FIFA FNDA-26976 (TQBVT_ITN02) ITSS-5334 - OPUS Offers does NOT trigger Credit Installation and Service Fees
- https://jira.tsl.telus.com/browse/FNDA-27289
- https://jira.tsl.telus.com/browse/FNDA-27138

- 900 Block  9136923654113578850
- Toll Block 9136923654113578856
  
--- 
<br/><br/><br/>


---
## FIFA FNDA-26976 (TQBVT_ITN02) ITSS-5334 - OPUS Offers does NOT trigger Credit Installation and Service Fees
- https://jira.tsl.telus.com/browse/FNDA-26976
- [link](./stuff/CLOSED/FNDA-26976/index.md)

- https://flcncapp-itn02.tsl.telus.com/ncobject.jsp?id=9164913939991407857
213510849

equals to optik tv: https://flcncapp-itn02.tsl.telus.com/ncobject.jsp?id=9165232588159114404
equals to tv:       https://flcncapp-itn02.tsl.telus.com/ncobject.jsp?id=9165232588105114403

--- 
<br/><br/><br/>



---
## FIFA FNDA-26910 [DMT_ITN02_E2E] The description of One-time charges and credits does not match the prices
- https://jira.tsl.telus.com/browse/FNDA-26910
- [link](./stuff/CLOSED/FNDA-26910/index.md)

--- 
<br/><br/><br/>




---
## FIFA FNDA-26779 DEC MJR_ITN02 | D2C | Partners | New Provide | Invalid promo code
- https://jira.tsl.telus.com/browse/FNDA-26779
- [link](./stuff/CLOSED/FNDA-26779/index.md)
  
--- 
<br/><br/><br/>



---
## FIFA FNDA-26920 [DMT_ITN02_E2E] Billing Action error Invalid ApIds: null00nyTC

- https://jira.tsl.telus.com/browse/FNDA-26920
- [link](./stuff/CLOSED/FNDA-26920/index.md)
  
--- 
<br/><br/><br/>



---
## FIFA FNDA-26817 [DMT_ITN02_E2E] Billing Action error Invalid ApIds: null00nw4g

- https://jira.tsl.telus.com/browse/FNDA-26817
- [link](./stuff/CLOSED/FNDA-26817/index.md)
  
--- 
<br/><br/><br/>






---
## FIFA FNDA-26470 (TQBVT_PROD) CSR - (Home Phone, Additional Directory Listing), Designation does NOT keep the pre-selected option

##     CR: CR Branch FNDA-26470 Designation does NOT keep the pre-selected option
## Branch: BRANCH FNDA-26470 Designation does NOT keep the pre-selected option


- https://jira.tsl.telus.com/browse/FNDA-26470
- [link](./stuff/CLOSED/FNDA-26470/index.md)

- NC Request to Flix Bulk: https://jira.tsl.telus.com/browse/FNDA-26599


- https://flcncapp-itn03.tsl.telus.com/ncobject.jsp?id=9165100702613224672
- erictest RBnovtenone


--- 
<br/><br/><br/>




---
## FIFA FNDA-25025 WiFi 6E Extender not added to PODS



- https://jira.tsl.telus.com/browse/FNDA-25025
- [link](./stuff/CLOSED/FNDA-25025/index.md)
  
--- 
<br/><br/><br/>



---
## TAFT 2.0 Delivery TAFT2-7277 [DMT_ST_DV27] "One-time" is not translated to French in Shopping Cart

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- Order processing charge --> 9164913578769407851
- Order processing charge --> 9164913548919303412

Frais de traitement de dossier
Frais de raccordement de ligne



- https://jira.tsl.telus.com/browse/TAFT2-7277
- [link](./stuff/CLOSED/TAFT2-7277/index.md)
  
--- 
<br/><br/><br/>


---
## TAFT 2.0 Delivery TAFT2-7278 [DMT_ST_DV27] It is not possible to remove 900 Block feature

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7278
- [link](./stuff/CLOSED/TAFT2-7277/index.md)
  
--- 
<br/><br/><br/>






---
## TAFT 2.0 Delivery B O T

##     CR: CR BOT Execution
## Branch: ITSS-4936 - Alignment of Tax Included Credits 

- DV35
- [link](./stuff/CLOSED/ROBOTAX/index.md)
  
- https://docs.google.com/spreadsheets/d/1OPwL9XbnQGKyujvoN-5dd4gU6aR7NVGe/edit##gid=8262681
  
--- 
<br/><br/><br/>


---
## TAFT 2.0 Delivery TAFT2-7173 - [PC] Apply Dormancy

##     CR: 
## Branch: 2022F12-DecemberMRBranch

- ITSS-4936 - Alignment of Tax Included Credits
  
- https://jira.tsl.telus.com/browse/TAFT2-7173
- [link](./stuff/CLOSED/TAFT2-7173/index.md) 

- https://docs.google.com/spreadsheets/d/1tL-gzaTd6dMns7Xo1EcgYuKuGcIL70Mk/edit##gid=254687718

- https://drive.google.com/file/d/1fmhIjEqXSTAhzsG0FhuH6ihorSFw_ezy/view
- Minute 27

- Iteration https://stackoverflow.com/questions/10798161/loop-through-pre-defined-values

- Rollback https://oracle-base.com/articles/misc/sql-for-beginners-the-insert-statement

## If dormancy is required to be applied in f12 branch before release night
  Remove CRs from f12 release branch:
- 0b712f63-7f4d-41f7-86da-a31d04423a60
- 78b5bca2-88f6-4015-9490-a03050e099e0

## Apply Dormancy 
- Execute Queries: delete.sql, insert.sql, update.sql in that order

## Apply Undormancy
- Execute Queries: undormant_delte.sql, undormant_insert.sql, undormant_update.sql in that order



--- 
<br/><br/><br/>


---
## TAFT 2.0 Delivery / TAFT2-7200 - [DMT_DV27_ST] Display Block should be available on csr

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7200


     CA: ccbp ccbp provNetTwo 
Address:  1 10 RUE DE L'ÉVÊCHÉ E, RIMOUSKI, QC

override_type	                            Do not override 
child_behavior	                            Retain 
sync_to_legacy_system	                    true 
action_to_modify_parent	                    Add,Delete 
propagate_modify_to_parent	                No 
propagate_override_to_all_child_offerings	Do not override 

--- 
<br/><br/><br/>


---
## TAFT 2.0 Delivery TAFT2-7072 - [PC] Enable Dormancy for LWC Price Increase ITSS-5487

##     CR: [TAFT] ITSS-5487 LWC Price Increase 
## Branch: 2022F11-NovemberMRBranch

- https://jira.tsl.telus.com/browse/TAFT2-7072
- [link](./stuff/CLOSED/TAFT2-7072/index.md) 

| Object_id           | Offer name                                               | Old billing offer id | Old price | New billing offer id | New price |
| :------------------ | :------------------------------------------------------- | :------------------- | :-------- | :------------------- | :-------- |
| 9161505374995984301 | LivingWell Companion Home with Fall Detection - Cellular | 41161921             | $50       | 41226331             | $55       |
| 9161505363905984296 | LivingWell Companion Home - Cellular                     | 41161911             | $40       | 41226321             | $45       |
| 9161482788965984291 | LivingWell Companion Go                                  | 41161931             | $60       | 41226341             | $65       |



--- 
<br/><br/><br/>








---
## TAFT 2.0 Delivery TAFT2-7056 - [PC] TFP-1429/ 900 Block & Toll Block removal fees

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7056
- [link](./stuff/CLOSED/TAFT2-7056/index.md)  

https://github.com/telus/nc-telus-fifa/pull/9401


//Original Rule
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/business-rule/fdd9aa0d-6ec2-4490-91cf-1fd75b746ab9/f3bbd3af-88aa-4527-ae88-cf6feb1ea2d0
Warn when “Software” delivery method is selected for LWC_CPQ

//Original Action
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-action/94258b33-f9c7-43ff-97bc-c61c94325614/f6d6157d-d9a0-4a2e-88e4-e0a93ccd40c1


//New Rule
Warn when “Remove” 900 Block & Toll Block because of additional fee
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/business-rule/eb1739ca-a3c3-4930-a29b-401c101088b6/3818118c-53ab-4acf-9e61-7c0a25418318


    //Condition 1
    TQ Voice plans (9159722947713609854) are new/current
    https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-condition/e4c2f30a-5331-4f84-82a3-6d917ed8f37d/3818118c-53ab-4acf-9e61-7c0a25418318

    //Condition 2
    900 Block (9136923654113578850) is deleted/selected
    https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-condition/d1a185f8-a8a2-4c11-a62d-470d8a33d33d/3818118c-53ab-4acf-9e61-7c0a25418318

    //Contidion 3
    Call Guardian - Toll Block (9136923654113578856) is deleted/selected
    https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-condition/bc8d330a-d953-4366-8ea3-c15ec57bd207/3818118c-53ab-4acf-9e61-7c0a25418318


    priority	               10 
    execute_on	               BE 
    is_bundle_only	           false 
    notification_type	       Warning  
    text_rule_parameter	       [{"CancelButton":"Cancel"}, {"ContinueButton":"Continue"}, {"Redirect URL":"/checkout"}]    
    sync_to_legacy_system	   true 
    execution_scope            customize_phone 



//New Action
Warn msg if “Remove” 900 Block & Toll Block
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-action/52f8ccfc-53c7-4ff4-a5a9-04e498f31e2e/3818118c-53ab-4acf-9e61-7c0a25418318

//Action Message
Fee will be added if remove 900 Block or Toll Block
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/rules/rule-action-message/51df4535-b658-428b-b542-62b2140725d9/3818118c-53ab-4acf-9e61-7c0a25418318
Reminder: A $10 fee is applicable for removing the blocking feature




qcntest qcntest
1 289 RUE GOSSELIN ST, RIMOUSKI, QC

dtestuser dtestuser
9164963017313198041
313903024
1 274 RUE GOSSELIN ST, RIMOUSKI, QC

--- 
<br/><br/><br/>










---
## FIFA FNDA-25620 - [BVT_ITN02] ITSS-5487 Price is not reflecting in enabler.

##     CR: [TAFT] ITSS-5487 LWC Price Increase 
## Branch: 2022F11-NovemberMRBranch

- https://jira.tsl.telus.com/browse/FNDA-25620
- [link](./stuff/CLOSED/FNDA-25620/index.md)  

- LivingWell Companion Home - Cellular (V2):                       9161505363905984296
- LivingWell Companion Home with Fall Detection - Cellular (V2):   9161505374995984301
- LivingWell Companion Go (V2):                                    9161482788965984291


Old BOID   Billing Offer Id	    Billing Offer Name
41161911   41226321	            LivingWell Companion Home - Cellular (V2)
41161921   41226331	            LivingWell Companion Home with Fall Detection - Cellular (V2)
41161931   41226341	            LivingWell Companion Go (V2)

Old Billing Offer ID


//Testing
CCBPlwc RBOcttwooneFOUR (no price in enabler)
124912247
telusbvt-09itssLWC@yahoo.com
32764, HAIDA DR Drive ABBOTSFORD, BC Canada

CCBPlwc RBOcttwooneTHREE(no price in enabler)
124912217
telusbvt-08itssLWC@yahoo.com
32765, HAIDA DR Drive ABBOTSFORD, BC Canada

CCBPlwc RBOcttwentyONE (no price in enabler)
124912175
telusbvt-06itssLWC@yahoo.com
32739, HAIDA DR Drive ABBOTSFORD, BC Canada

--- 
<br/><br/><br/>































---
## FIFA FNDA-25579 - [DMT_ITN02_E2E] LWC Create Subscriber Error - No rows returned for 4120617

##     CR: [TAFT] ITSS-5487 LWC Price Increase
## Branch: [TAFT] ITSS-5487 LWC Price Increase 


- https://jira.tsl.telus.com/browse/FNDA-25579
- [link](./stuff/CLOSED/FNDA-25579/index.md)


LivingWell Companion Go - With App
https://flcncapp-itn02.tsl.telus.com/common/uobject.jsp?tab=_Price&object=9163210145801646781

select * from nc_params where object_id = 9164750501316234960 and attr_id = 9141216061213794878;
update nc_params set VALUE = 41206171 where object_id = 9164750501316234960 and attr_id = 9141216061213794878;

--- 
<br/><br/><br/>
















---
## TAFT 2.0 Delivery TAFT2-7133 - [PC] TFP-2116/ 3rd Number Block

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7133
- [link](./stuff/CLOSED/TAFT2-7133/index.md)  

//Original Template
Call Guardian - 3rd Number Billing Block-Portal Configuration-2
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/ba1fc613-6497-20cd-6a4c-c6c928574111/207762ee-dd0a-4386-bdd4-74a967836320

//Original Offer
Call Guardian - 3rd Number Billing Block-1
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/7d7ebec3-7bee-c833-e75d-5d31b07b615a/207762ee-dd0a-4386-bdd4-74a967836320


//Cloned Template
3rd Number Block Template
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/afc9e6a6-386a-42e0-a82e-46d867b41955/3818118c-53ab-4acf-9e61-7c0a25418318

//New Product Offering
3rd Number Block feature offer
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/c0012f52-866f-44e5-9be3-17d1aba7bb29/3818118c-53ab-4acf-9e61-7c0a25418318

## *** TOP OFFERS ***

## Extended Parameters of Relation

override_type                               Do not override 
child_behavior                              Retain 
sync_to_legacy_system                       true 
action_to_modify_parent                     Add,Delete,Modify
propagate_modify_to_parent                  No 
propagate_override_to_all_child_offerings   Do not override 

TQ Home phone-Template
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/8c3585ca-d214-4f2a-bcaa-bc247c1ceadb/d80f3bcd-d78f-4aed-9740-90f14e7e0a63

Home Phone Lite
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/a05ba9eb-53f8-4c18-94d9-87e4f8a75351/d80f3bcd-d78f-4aed-9740-90f14e7e0a63

TQ Home phone-Template
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/8c3585ca-d214-4f2a-bcaa-bc247c1ceadb/d80f3bcd-d78f-4aed-9740-90f14e7e0a63

Home Phone-7
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/4087486a-ed6c-4e8a-b5e3-8fdf2f4d8375/191b45ba-1c88-4af8-86c7-03be9fd3b7e9

--- 
<br/><br/><br/>


---
## TAFT 2.0 Delivery TAFT2-7052 - [PC] TFP-2114/ Add Display Block feature offer

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7052
- [link](./stuff/CLOSED/TAFT2-7052/index.md)  

//Original Template
Display Block-Portal Configuration 
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/6daf2e18-b45a-bb87-a279-78d76fd4434c/207762ee-dd0a-4386-bdd4-74a967836320

//Original Offer
Display Block
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/c986ae06-0df8-059c-6dca-3b712ec6b24d/207762ee-dd0a-4386-bdd4-74a967836320


//Cloned Template
Add Disp Block feature offer Template
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/90d365a0-780c-42ea-9ef9-a19a267c501d/3818118c-53ab-4acf-9e61-7c0a25418318

//New Product Offering
Add Disp Block feature offer
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/5a36fddc-dfa5-495c-b442-7ca614470967/3818118c-53ab-4acf-9e61-7c0a25418318

//Extended Parameters

source_id	                      
sku_char_id	
suspendable	                     Yes
reliable_asset	                 Yes 
billing_offer_id	
sync_to_legacy_system            false 
assigned_product_id_prefix	     A1kB 
can_be_automatically_moved_to	
applicable_for_manual_discount	 Yes 


TQ Home phone-Template
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/templates/product-offering-template/8c3585ca-d214-4f2a-bcaa-bc247c1ceadb/d80f3bcd-d78f-4aed-9740-90f14e7e0a63

Home Phone Lite
https://pim-frontend-srv-cloud-bss-pr01.nc-gke-pr.tsl.telus.com/##/offerings/product-offering/a05ba9eb-53f8-4c18-94d9-87e4f8a75351/d80f3bcd-d78f-4aed-9740-90f14e7e0a63



TELUS_Offering_External_IDs (TELUS BAU)
https://docs.google.com/spreadsheets/d/1kwcPw6wsZFN6VQ4Iaq03nXI0Jw7_UFto-2132wj_SMA/edit##gid=1920647907

--- 
<br/><br/><br/>











---
## TAFT 2.0 Delivery TAFT2-7054 - [PC] TFP-2115/ Changes for Toll Block offer
           
##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7054
- [link](./stuff/CLOSED/TAFT2-7054/loc.txt)  

## Address
- 9164896080913553579
- Formated address: 1 419 RUE DU FLEUVE ST, RIMOUSKI, QC
- qctoll qctoll

- TQ Home phone lite 9162909276385310484
- Toll Block offer   9136923654113578856

- Call Guardian - Toll Block-Portal
  
## Extended Parameters
override_type                               Do not override 
child_behavior                              Retain 
sync_to_legacy_system                       true 
action_to_modify_parent                     Add,Delete 
propagate_modify_to_parent                  No 
propagate_override_to_all_child_offerings   Do not override 

--- 
<br/><br/><br/>



---
## TAFT 2.0 Delivery TAFT2-7053 - [PC] TFP-2113/ Changes for 900 Block offer

##     CR: [TAFT] ITSS-5334 / CSR Portal/Netcracker changes for NGHP project
## Branch: ITSS-5334 / CSR Portal/Netcracker changes for NGHP project

- https://jira.tsl.telus.com/browse/TAFT2-7053
- [link](./stuff/CLOSED/TAFT2-7053/loc.txt)     

## Address
- 9164868905813509134
- Formated address: 1 547 RUE DU FLEUVE ST, RIMOUSKI, QC
- DV27 - ECID: 313746547
- frienxin frienxin

--- 
<br/><br/><br/>








































---
## TAFT 2.0 Delivery TAFT2-6706 - [PC] Price increase for LWC MPERS
- https://jira.tsl.telus.com/browse/TAFT2-6706
  
##     CR: [TAFT] ITSS 5487 LWC Price increase v2
## Branch: [TAFT] ITSS 5487 LWC Price increase HLD

- Grandfather 9163210145801646781
- New         9164602490600317395 

- Anx5
- A new Product assigned prefix must be taken from spreadsheet
- https://docs.google.com/spreadsheets/d/1kwcPw6wsZFN6VQ4Iaq03nXI0Jw7_UFto-2132wj_SMA/edit?usp=sharing

--- 
<br/><br/><br/>







---
## TAFT 2.0 Delivery TAFT2-6709 - [PC] Price increase for LWC Home with fall detection - cellular
- https://jira.tsl.telus.com/browse/TAFT2-6709

##     CR: [TAFT] ITSS 5487 LWC Price increase v2
## Branch: [TAFT] ITSS 5487 LWC Price increase HLD

- DV51

- Grandfather 9161505374995984301
- New         9164611847674675369

- AnxC
- A new Product assigned prefix must be taken from spreadsheet
- https://docs.google.com/spreadsheets/d/1kwcPw6wsZFN6VQ4Iaq03nXI0Jw7_UFto-2132wj_SMA/edit?usp=sharing

- Change Request: [TAFT] ITSS 5487 LWC Price increase v2
- Branch:         [TAFT] ITSS 5487 LWC Price increase HLD
  
--- 
<br/><br/><br/>












---
## TAFT 2.0 Delivery TAFT2-6707 - [PC] Align Rule reference from LWC MPERS
- https://jira.tsl.telus.com/browse/TAFT2-6707

##     CR: [TAFT] ITSS 5487 LWC Price increase v2
## Branch: [TAFT] ITSS 5487 LWC Price increase HLD

--- 
<br/><br/><br/>












---
## FIFA FNDA-23987 (TQBVT_ITN02) CSR - directory listing & Additional Directory Listing has duplicate options
- https://jira.tsl.telus.com/browse/FNDA-23987
- [link](./stuff/CLOSED/FNDA-23987/)            

--- 
<br/><br/><br/>












---
## FIFA Catalog Management - CMFBP-23041 - Add "Software" to Wi-Fi 6E Extender offering
- https://jira.tsl.telus.com/browse/CMFBP-23041

##     CR: CR CMFBP-23041 Add "Software" to Wi-Fi 6E Extender offering
## Branch: CR CMFBP-23041 Add "Software" to Wi-Fi 6E Extender offering



--- 
<br/><br/><br/>












---
## FIFA FNDA-24371 - (TQBVT_ITN02) - CSR - Directory Listing not translated
- https://jira.tsl.telus.com/browse/FNDA-24371
  
- https://flcncapp-itn02.tsl.telus.com/common/uobject.jsp?tab=_Portal+Content&object=9164020405428562786 
- https://flcncapp-dv52.tsl.telus.com/common/uobject.jsp?tab=_Portal+Content&object=9164020405428562786 





--- 
<br/><br/><br/>












---
## FIFA FNDA - 24592 (TQBVT_PROD) CSR - Missing "Other" option under "Title" for Name Listing & Additional Directory Listing
- https://jira.tsl.telus.com/browse/FNDA-24592

##     CR: [TAFT] CR FNDA - 24592 Directory Listing Missing Other
## Branch: [TAFT] FNDA - 24592 Directory Listing Missing Other

## Directory Listing
- https://flcncapp-dv27.tsl.telus.com/ncobject.jsp?id=9164020405428562786 

## Additional Directory Listing
- https://flcncapp-dv27.tsl.telus.com/ncobject.jsp?id=9164022378661450533

- https://flcncapp-pr.tsl.telus.com/common/uobject.jsp?object=1000

B 4 RUE JULES-A.-BRILLANT, RIMOUSKI, QC
qctigon



--- 
<br/><br/><br/>












---
## TAFT 2.0 Delivery TAFT2-6814 - [PC] Prepare DV27 to not sync Retain Historical Price parameter
- https://jira.tsl.telus.com/browse/TAFT2-6814
  
- ## Additional Directory Listing
- https://flcncapp-dv27.tsl.telus.com/ncobject.jsp?id=9164022378661450533
  
--- 
<br/><br/><br/>












---
## TAFT 2.0 Delivery - TAFT2-6816 - [PC] Price increase on LWC Offers
- https://jira.tsl.telus.com/browse/TAFT2-6816
- 
- 
##     CR: [TAFT] ITSS-5487 LWC Price Increase
## Branch: [TAFT] ITSS-5487 LWC Price Increase 

Create new price key for offers and expire current price:

LivingWell Companion Go - $65 (9161482788965984291)
LivingWell Companion Go - With App - $75 (9163210145801646781)

Validation for unit testing:

1- New provide after price increase:
In the billing request .xml for create subscriber, the new  billing offer id must be sent for the LWC top offer.

2- Modify existing customer

For an existing customer before price increase, take one customer from the Prerequisites, perform a modify order for example add a new equipment or change top offer then complete order.

Expected result: No modify billing action should be generated for LWC Top offer, and if one is generated the old billing offer id must be sent in request.


firstqb
4851247956

seconqb
4854215478


--- 
<br/><br/><br/>












---
## TAFT 2.0 Delivery - TAFT2-6892 - Remove Tax Code for all Tax Included Promotions from Non-TV
- https://jira.tsl.telus.com/browse/TAFT2-6892

- https://docs.google.com/spreadsheets/d/1tL-gzaTd6dMns7Xo1EcgYuKuGcIL70Mk/edit##gid=254687718

- [link](./stuff/CLOSED/TAFT2-6892/)    
- CR: ITSS-4936 - Alignment of Tax Included Credits v2
- Branch: ITSS-4936 - Alignment of Tax Included Credits 

--- 
<br/><br/><br/>
